"""initial schema: users, assessments, mowers, recommendations, leads.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-01

This migration creates the full Phase 1 schema. Hand-written rather than
autogenerated to keep PostGIS extension installation deterministic and to lay
out the indexes called out in Section 4.3 of the build spec.
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- Enum value tuples (kept in sync with app.models.enums) ----------------- #
USER_ROLES = ("homeowner", "sales_rep", "admin")
ASSESSMENT_STATUSES = ("draft", "completed", "abandoned")
NAV_TYPES = ("wire", "rtk", "vision", "lidar", "hybrid")
DRIVE_TYPES = ("2wd", "awd", "tracks")
FIT_STATUSES = ("green", "yellow", "red")
PREF_CONTACTS = ("email", "phone", "either")
LEAD_STATUSES = ("new", "contacted", "qualified", "sold", "lost")


def upgrade() -> None:
    # PostGIS — required for Geography column on assessments.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')  # for gen_random_uuid()

    # ---------- users ---------- #
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("clerk_id", sa.String(64), nullable=True),
        sa.Column("email", sa.String(320), nullable=True),
        sa.Column(
            "role",
            sa.String(32),
            nullable=False,
            server_default="homeowner",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(f"role IN {USER_ROLES}", name="ck_users_role"),
        sa.UniqueConstraint("clerk_id", name="uq_users_clerk_id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_clerk_id", "users", ["clerk_id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=False)

    # ---------- mowers ---------- #
    op.create_table(
        "mowers",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("brand", sa.String(64), nullable=False),
        sa.Column("model", sa.String(128), nullable=False),
        sa.Column("slug", sa.String(160), nullable=False),
        sa.Column("price_usd", sa.Float(), nullable=False),
        sa.Column("max_area_sqft", sa.Integer(), nullable=False),
        sa.Column("max_slope_pct", sa.Integer(), nullable=False),
        sa.Column("min_passage_inches", sa.Float(), nullable=False),
        sa.Column("navigation_type", sa.String(16), nullable=False),
        sa.Column("drive_type", sa.String(16), nullable=False),
        sa.Column("cutting_width_inches", sa.Float(), nullable=False),
        sa.Column("cutting_height_min", sa.Float(), nullable=False),
        sa.Column("cutting_height_max", sa.Float(), nullable=False),
        sa.Column("battery_minutes", sa.Integer(), nullable=False),
        sa.Column("noise_db", sa.Integer(), nullable=True),
        sa.Column("rain_handling", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "has_gps_theft_protection",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column("product_url", sa.String(1024), nullable=False),
        sa.Column("affiliate_url", sa.String(1024), nullable=True),
        sa.Column("image_url", sa.String(1024), nullable=False),
        sa.Column("manufacturer_specs_url", sa.String(1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "data_updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(f"navigation_type IN {NAV_TYPES}", name="ck_mowers_nav"),
        sa.CheckConstraint(f"drive_type IN {DRIVE_TYPES}", name="ck_mowers_drive"),
        sa.CheckConstraint("price_usd >= 0", name="ck_mowers_price"),
        sa.CheckConstraint("max_area_sqft > 0", name="ck_mowers_area"),
        sa.CheckConstraint("max_slope_pct >= 0", name="ck_mowers_slope"),
        sa.UniqueConstraint("slug", name="uq_mowers_slug"),
    )
    op.create_index("ix_mowers_slug", "mowers", ["slug"], unique=False)
    op.create_index("ix_mowers_brand_model", "mowers", ["brand", "model"], unique=False)
    op.create_index(
        "ix_mowers_active_max_area",
        "mowers",
        ["is_active", "max_area_sqft"],
        unique=False,
    )

    # ---------- assessments ---------- #
    op.create_table(
        "assessments",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("session_id", sa.String(64), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="draft"),
        sa.Column("address", sa.String(512), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column(
            "lawn_polygon",
            Geography(geometry_type="POLYGON", srid=4326, spatial_index=False),
            nullable=True,
        ),
        sa.Column("lawn_area_sqft", sa.Float(), nullable=True),
        sa.Column("max_slope_pct", sa.Float(), nullable=True),
        sa.Column("avg_slope_pct", sa.Float(), nullable=True),
        sa.Column(
            "slope_samples",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "grass_type_guesses",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("grass_photo_url", sa.String(1024), nullable=True),
        sa.Column(
            "obstacles",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "gates",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(f"status IN {ASSESSMENT_STATUSES}", name="ck_assessments_status"),
    )
    op.create_index(
        "ix_assessments_user_created",
        "assessments",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_assessments_session_id", "assessments", ["session_id"], unique=False)
    op.execute(
        "CREATE INDEX ix_assessments_lawn_polygon ON assessments USING gist (lawn_polygon)"
    )

    # ---------- recommendations ---------- #
    op.create_table(
        "recommendations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "assessment_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("assessments.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "mower_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("mowers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("fit_score", sa.Integer(), nullable=False),
        sa.Column("fit_status", sa.String(16), nullable=False),
        sa.Column(
            "reasons",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(f"fit_status IN {FIT_STATUSES}", name="ck_recs_fit_status"),
        sa.CheckConstraint("fit_score BETWEEN 0 AND 100", name="ck_recs_fit_score_range"),
        sa.UniqueConstraint("assessment_id", "mower_id", name="uq_recommendation_per_mower"),
    )
    op.create_index(
        "ix_recommendations_assessment_rank",
        "recommendations",
        ["assessment_id", "rank"],
        unique=False,
    )

    # ---------- leads ---------- #
    op.create_table(
        "leads",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "assessment_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("assessments.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("phone", sa.String(32), nullable=True),
        sa.Column(
            "preferred_contact",
            sa.String(16),
            nullable=False,
            server_default="email",
        ),
        sa.Column("notes", sa.String(2000), nullable=True),
        sa.Column(
            "zippylawnz_status",
            sa.String(16),
            nullable=False,
            server_default="new",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            f"preferred_contact IN {PREF_CONTACTS}", name="ck_leads_preferred_contact"
        ),
        sa.CheckConstraint(
            f"zippylawnz_status IN {LEAD_STATUSES}", name="ck_leads_status"
        ),
        sa.UniqueConstraint("assessment_id", name="uq_leads_assessment"),
    )
    op.create_index("ix_leads_email", "leads", ["email"], unique=False)
    op.create_index(
        "ix_leads_status_created",
        "leads",
        ["zippylawnz_status", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_leads_status_created", table_name="leads")
    op.drop_index("ix_leads_email", table_name="leads")
    op.drop_table("leads")

    op.drop_index("ix_recommendations_assessment_rank", table_name="recommendations")
    op.drop_table("recommendations")

    op.execute("DROP INDEX IF EXISTS ix_assessments_lawn_polygon")
    op.drop_index("ix_assessments_session_id", table_name="assessments")
    op.drop_index("ix_assessments_user_created", table_name="assessments")
    op.drop_table("assessments")

    op.drop_index("ix_mowers_active_max_area", table_name="mowers")
    op.drop_index("ix_mowers_brand_model", table_name="mowers")
    op.drop_index("ix_mowers_slug", table_name="mowers")
    op.drop_table("mowers")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_clerk_id", table_name="users")
    op.drop_table("users")
    # Leave PostGIS / pgcrypto installed — they may be used by other things.
